In [61]:
from limpeza import data_cleaning

In [62]:
df = data_cleaning("../data/dataset_01_parceiroA.csv")
df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-01-01,grupo_1,parceiro_a,196,10273,3267,93390
1,2011-01-02,grupo_1,parceiro_a,115,7555,2060,68682
2,2011-01-03,grupo_1,parceiro_a,82,4839,1358,43993
3,2011-01-04,grupo_1,parceiro_a,172,10419,2907,94722
4,2011-01-05,grupo_1,parceiro_a,187,11305,3138,102768

In [63]:
df["grupos_de_usuários"].unique()

<StringArray>
['grupo_1', 'grupo_2', 'grupo_3']
Length: 3, dtype: str

In [64]:
df_grupo1 = df[df["grupos_de_usuários"] == "grupo_1"]
df_grupo2 = df[df["grupos_de_usuários"] == "grupo_2"]
df_grupo3 = df[df["grupos_de_usuários"] == "grupo_3"]

## Lucro Líquido

In [65]:
comissao_grp1 = df_grupo1["comissão"].sum()
cashback_grp1 = df_grupo1["cashback"].sum()

print(comissao_grp1, cashback_grp1)

lucro_liquido_grp1 = comissao_grp1 - cashback_grp1

638135 233424

In [66]:
comissao_grp2 = df_grupo2["comissão"].sum()
cashback_grp2 = df_grupo2["cashback"].sum()

print(comissao_grp2, cashback_grp2)

lucro_liquido_grp2 = comissao_grp2 - cashback_grp2

728178 370659

In [67]:
comissao_grp3 = df_grupo3["comissão"].sum()
cashback_grp3 = df_grupo3["cashback"].sum()

print(comissao_grp3, cashback_grp3)

lucro_liquido_grp3 = comissao_grp3 - cashback_grp3

767887 503600

In [68]:
print(f"Lucro líquido do grupo 1: {lucro_liquido_grp1}")
print(f"Lucro líquido do grupo 2: {lucro_liquido_grp2}")
print(f"Lucro líquido do grupo 3: {lucro_liquido_grp3}")

Lucro líquido do grupo 1: 404711
Lucro líquido do grupo 2: 357519
Lucro líquido do grupo 3: 264287

### ROI

In [69]:
df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-01-01,grupo_1,parceiro_a,196,10273,3267,93390
1,2011-01-02,grupo_1,parceiro_a,115,7555,2060,68682
2,2011-01-03,grupo_1,parceiro_a,82,4839,1358,43993
3,2011-01-04,grupo_1,parceiro_a,172,10419,2907,94722
4,2011-01-05,grupo_1,parceiro_a,187,11305,3138,102768

In [70]:
roi_grp1 = lucro_liquido_grp1 / cashback_grp1
roi_grp2 = lucro_liquido_grp2 / cashback_grp2
roi_grp3 = lucro_liquido_grp3 / cashback_grp3

print(f"ROI grupo 1: {roi_grp1:.2f}\nROI grupo 2: {roi_grp2:.2f}\nROI grupo 3: {roi_grp3:.2f}")

ROI grupo 1: 1.73
ROI grupo 2: 0.96
ROI grupo 3: 0.52

## Lucro médio por comprador

In [71]:
total_compradores_grp1 = df_grupo1["compradores"].sum()
lucro_medio_comprador_grp1 = lucro_liquido_grp1 / total_compradores_grp1

total_compradores_grp2 = df_grupo2["compradores"].sum()
lucro_medio_comprador_grp2 = lucro_liquido_grp2 / total_compradores_grp2

total_compradores_grp3 = df_grupo3["compradores"].sum()
lucro_medio_comprador_grp3 = lucro_liquido_grp3 / total_compradores_grp3

print(f"Lucro médio por comprador grupo 1: {lucro_medio_comprador_grp1:.2f}\nLucro médio por comprador grupo 2: {lucro_medio_comprador_grp2:.2f}\nLucro médio por comprador grupo 3: {lucro_medio_comprador_grp3:.2f}")

Lucro médio por comprador grupo 1: 42.01
Lucro médio por comprador grupo 2: 33.06
Lucro médio por comprador grupo 3: 23.16

# Guardrails

## GMV: Valor total das vendas

In [72]:
df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-01-01,grupo_1,parceiro_a,196,10273,3267,93390
1,2011-01-02,grupo_1,parceiro_a,115,7555,2060,68682
2,2011-01-03,grupo_1,parceiro_a,82,4839,1358,43993
3,2011-01-04,grupo_1,parceiro_a,172,10419,2907,94722
4,2011-01-05,grupo_1,parceiro_a,187,11305,3138,102768

In [73]:
gmv_grp1 = df_grupo1["vendas_totais"].sum()
gmv_grp2 = df_grupo2["vendas_totais"].sum()
gmv_grp3 = df_grupo3["vendas_totais"].sum()


print(f"Vendas totais grupo 1: {gmv_grp1}\nVendas totais grupo 2: {gmv_grp2}\nVendas totais grupo 3: {gmv_grp3}")

Vendas totais grupo 1: 5605173
Vendas totais grupo 2: 6423096
Vendas totais grupo 3: 6785856

## Compradores totais

In [74]:

print(f"Total de compradores grupo 1: {total_compradores_grp1}\nTotal de compradores grupo 2: {total_compradores_grp2}\nTotal de compradores grupo 3: {total_compradores_grp3}")

Total de compradores grupo 1: 9633
Total de compradores grupo 2: 10814
Total de compradores grupo 3: 11410

----------------------------------------------------------

## Fluxo simplificado

In [ ]:
df_agrupado = df.groupby("grupos_de_usuários").agg({
    "comissão": "sum",
    "cashback": "sum",
    "compradores": "sum",
    "vendas_totais": "sum"
})
df_agrupado

                    comissão  cashback  compradores  vendas_totais
grupos_de_usuários
grupo_1               638135    233424         9633        5605173
grupo_2               728178    370659        10814        6423096
grupo_3               767887    503600        11410        6785856

In [81]:
df_kpis = (
    df.groupby("grupos_de_usuários")
    .agg({
        "comissão": "sum",
        "cashback": "sum",
        "compradores": "sum",
        "vendas_totais": "sum",
    })
    .reset_index()
)

df_kpis["lucro_liquido_total"] = df_kpis["comissão"] - df_kpis["cashback"]
df_kpis["roi"] = df_kpis["lucro_liquido_total"] / df_kpis["cashback"]
df_kpis["lucro_por_comprador"] = df_kpis["lucro_liquido_total"] / df_kpis["compradores"]
df_kpis["gmv"] = df_kpis["vendas_totais"]

df_kpis

,grupos_de_usuários,comissão,cashback,compradores,vendas_totais,lucro_liquido_total,roi,lucro_por_comprador,gmv
0,grupo_1,638135,233424,9633,5605173,404711,1.733802,42.012976,5605173
1,grupo_2,728178,370659,10814,6423096,357519,0.964550,33.060755,6423096
2,grupo_3,767887,503600,11410,6785856,264287,0.524795,23.162752,6785856