In [1]:
import sys
import pandas as pd
sys.path.append("../src")

from limpeza import data_cleaning

In [2]:
df = data_cleaning("../data/dataset_03_parceiroC.csv")
df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-07-01,grupo_1,parceiro_c,101,2911,2079,41585
1,2011-07-02,grupo_1,parceiro_c,57,1774,1267,25347
2,2011-07-03,grupo_1,parceiro_c,72,2083,1488,29761
3,2011-07-04,grupo_1,parceiro_c,123,3495,2497,49930
4,2011-07-05,grupo_1,parceiro_c,102,2247,1605,32093

In [3]:
df["grupos_de_usuários"].unique()

<StringArray>
['grupo_1', 'grupo_2']
Length: 2, dtype: str

In [4]:
df_grupo1 = df[df["grupos_de_usuários"] == "grupo_1"]
df_grupo2 = df[df["grupos_de_usuários"] == "grupo_2"]
df_grupo3 = df[df["grupos_de_usuários"] == "grupo_3"]

## Lucro Líquido

In [5]:
comissao_grp1 = df_grupo1["comissão"].sum()
cashback_grp1 = df_grupo1["cashback"].sum()

print(comissao_grp1, cashback_grp1)

lucro_liquido_grp1 = comissao_grp1 - cashback_grp1

121693 86924

In [6]:
comissao_grp2 = df_grupo2["comissão"].sum()
cashback_grp2 = df_grupo2["cashback"].sum()

print(comissao_grp2, cashback_grp2)

lucro_liquido_grp2 = comissao_grp2 - cashback_grp2

117967 117967

In [7]:
comissao_grp3 = df_grupo3["comissão"].sum()
cashback_grp3 = df_grupo3["cashback"].sum()

print(comissao_grp3, cashback_grp3)

lucro_liquido_grp3 = comissao_grp3 - cashback_grp3

0 0

In [8]:
print(f"Lucro líquido do grupo 1: {lucro_liquido_grp1}")
print(f"Lucro líquido do grupo 2: {lucro_liquido_grp2}")
print(f"Lucro líquido do grupo 3: {lucro_liquido_grp3}")

Lucro líquido do grupo 1: 34769
Lucro líquido do grupo 2: 0
Lucro líquido do grupo 3: 0

### ROI

In [9]:
df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-07-01,grupo_1,parceiro_c,101,2911,2079,41585
1,2011-07-02,grupo_1,parceiro_c,57,1774,1267,25347
2,2011-07-03,grupo_1,parceiro_c,72,2083,1488,29761
3,2011-07-04,grupo_1,parceiro_c,123,3495,2497,49930
4,2011-07-05,grupo_1,parceiro_c,102,2247,1605,32093

In [10]:
roi_grp1 = lucro_liquido_grp1 / cashback_grp1
roi_grp2 = lucro_liquido_grp2 / cashback_grp2
roi_grp3 = lucro_liquido_grp3 / cashback_grp3

print(f"ROI grupo 1: {roi_grp1:.2f}\nROI grupo 2: {roi_grp2:.2f}\nROI grupo 3: {roi_grp3:.2f}")

ROI grupo 1: 0.40
ROI grupo 2: 0.00
ROI grupo 3: nan

C:\Users\gabriel.pinho\AppData\Local\Temp\ipykernel_18496\3896600774.py:3: RuntimeWarning: invalid value encountered in scalar divide
  roi_grp3 = lucro_liquido_grp3 / cashback_grp3

## Lucro médio por comprador

In [11]:
total_compradores_grp1 = df_grupo1["compradores"].sum()
lucro_medio_comprador_grp1 = lucro_liquido_grp1 / total_compradores_grp1

total_compradores_grp2 = df_grupo2["compradores"].sum()
lucro_medio_comprador_grp2 = lucro_liquido_grp2 / total_compradores_grp2

total_compradores_grp3 = df_grupo3["compradores"].sum()
lucro_medio_comprador_grp3 = lucro_liquido_grp3 / total_compradores_grp3

print(f"Lucro médio por comprador grupo 1: {lucro_medio_comprador_grp1:.2f}\nLucro médio por comprador grupo 2: {lucro_medio_comprador_grp2:.2f}\nLucro médio por comprador grupo 3: {lucro_medio_comprador_grp3:.2f}")

Lucro médio por comprador grupo 1: 7.64
Lucro médio por comprador grupo 2: 0.00
Lucro médio por comprador grupo 3: nan

C:\Users\gabriel.pinho\AppData\Local\Temp\ipykernel_18496\2629316946.py:8: RuntimeWarning: invalid value encountered in scalar divide
  lucro_medio_comprador_grp3 = lucro_liquido_grp3 / total_compradores_grp3

# Guardrails

## GMV: Valor total das vendas

In [12]:
df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-07-01,grupo_1,parceiro_c,101,2911,2079,41585
1,2011-07-02,grupo_1,parceiro_c,57,1774,1267,25347
2,2011-07-03,grupo_1,parceiro_c,72,2083,1488,29761
3,2011-07-04,grupo_1,parceiro_c,123,3495,2497,49930
4,2011-07-05,grupo_1,parceiro_c,102,2247,1605,32093

In [13]:
gmv_grp1 = df_grupo1["vendas_totais"].sum()
gmv_grp2 = df_grupo2["vendas_totais"].sum()
gmv_grp3 = df_grupo3["vendas_totais"].sum()


print(f"Vendas totais grupo 1: {gmv_grp1}\nVendas totais grupo 2: {gmv_grp2}\nVendas totais grupo 3: {gmv_grp3}")

Vendas totais grupo 1: 1738460
Vendas totais grupo 2: 1685235
Vendas totais grupo 3: 0

## Compradores totais

In [14]:

print(f"Total de compradores grupo 1: {total_compradores_grp1}\nTotal de compradores grupo 2: {total_compradores_grp2}\nTotal de compradores grupo 3: {total_compradores_grp3}")

Total de compradores grupo 1: 4549
Total de compradores grupo 2: 4522
Total de compradores grupo 3: 0

----------------------------------------------------------

## Fluxo simplificado

In [15]:
df_agrupado = df.groupby("grupos_de_usuários").agg({
    "comissão": "sum",
    "cashback": "sum",
    "compradores": "sum",
    "vendas_totais": "sum"
}
)
df_agrupado

                    comissão  cashback  compradores  vendas_totais
grupos_de_usuários
grupo_1               121693     86924         4549        1738460
grupo_2               117967    117967         4522        1685235

In [16]:
df_kpis = (
    df.groupby("grupos_de_usuários")
    .agg({
        "comissão": "sum",
        "cashback": "sum",
        "compradores": "sum",
        "vendas_totais": "sum",
    })
    .reset_index()
)

df_kpis["lucro_liquido_total"] = df_kpis["comissão"] - df_kpis["cashback"]
df_kpis["roi"] = df_kpis["lucro_liquido_total"] / df_kpis["cashback"]
df_kpis["lucro_por_comprador"] = df_kpis["lucro_liquido_total"] / df_kpis["compradores"]
df_kpis["gmv"] = df_kpis["vendas_totais"]

df_kpis

,grupos_de_usuários,comissão,cashback,compradores,vendas_totais,lucro_liquido_total,roi,lucro_por_comprador,gmv
0,grupo_1,121693,86924,4549,1738460,34769,0.399993,7.643218,1738460
1,grupo_2,117967,117967,4522,1685235,0,0.000000,0.000000,1685235