In [3]:
import pandas as pd

In [4]:
df_ini = pd.read_csv("../data/dataset_01_parceiroA.csv")
df_ini

,Data,Grupos de usuários,Parceiro,compradores,comissão,cashback,vendas totais
0,2011-01-01,Grupo 1,Parceiro A,196,R$ 10.273,R$ 3.267,R$ 93.390
1,2011-01-02,Grupo 1,Parceiro A,115,R$ 7.555,R$ 2.060,R$ 68.682
2,2011-01-03,Grupo 1,Parceiro A,82,R$ 4.839,R$ 1.358,R$ 43.993
3,2011-01-04,Grupo 1,Parceiro A,172,R$ 10.419,R$ 2.907,R$ 94.722
4,2011-01-05,Grupo 1,Parceiro A,187,R$ 11.305,R$ 3.138,R$ 102.768
...,...,...,...,...,...,...,...
271,2011-03-29,Grupo 3,Parceiro A,72,R$ 3.769,R$ 1.713,R$ 34.267
272,2011-03-30,Grupo 3,Parceiro A,70,R$ 4.639,R$ 2.109,R$ 42.171
273,2011-03-31,Grupo 3,Parceiro A,88,R$ 5.812,R$ 2.642,R$ 52.836
274,2011-04-01,Grupo 3,Parceiro A,74,R$ 5.566,R$ 2.530,R$ 50.600
275,2011-04-02,Grupo 3,Parceiro A,61,R$ 3.860,R$ 1.754,R$ 35.087

In [5]:
df = df_ini.copy(deep=True)
df.head()

,Data,Grupos de usuários,Parceiro,compradores,comissão,cashback,vendas totais
0,2011-01-01,Grupo 1,Parceiro A,196,R$ 10.273,R$ 3.267,R$ 93.390
1,2011-01-02,Grupo 1,Parceiro A,115,R$ 7.555,R$ 2.060,R$ 68.682
2,2011-01-03,Grupo 1,Parceiro A,82,R$ 4.839,R$ 1.358,R$ 43.993
3,2011-01-04,Grupo 1,Parceiro A,172,R$ 10.419,R$ 2.907,R$ 94.722
4,2011-01-05,Grupo 1,Parceiro A,187,R$ 11.305,R$ 3.138,R$ 102.768

In [6]:
df.isna().sum()

Data                  0
Grupos de usuários    0
Parceiro              0
compradores           0
comissão              0
cashback              0
vendas totais         0
dtype: int64

In [7]:
# Tratando nome das colunas

df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")
df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-01-01,Grupo 1,Parceiro A,196,R$ 10.273,R$ 3.267,R$ 93.390
1,2011-01-02,Grupo 1,Parceiro A,115,R$ 7.555,R$ 2.060,R$ 68.682
2,2011-01-03,Grupo 1,Parceiro A,82,R$ 4.839,R$ 1.358,R$ 43.993
3,2011-01-04,Grupo 1,Parceiro A,172,R$ 10.419,R$ 2.907,R$ 94.722
4,2011-01-05,Grupo 1,Parceiro A,187,R$ 11.305,R$ 3.138,R$ 102.768

In [8]:
# Tratando colunas inteiras
df["comissão"] = df["comissão"].str.replace("$", "").str.replace(".", "").str.strip().str.replace("R", "")
df["cashback"] = df["cashback"].str.replace("$", "").str.replace(".", "").str.strip().str.replace("R", "")
df["vendas_totais"] = df["vendas_totais"].str.replace("$", "").str.replace(".", "").str.strip().str.replace("R", "")

# Tratando colunas str
df["grupos_de_usuários"] = df["grupos_de_usuários"].str.lower().str.strip().str.replace(" ", "_")
df["parceiro"] = df["parceiro"].str.lower().str.strip().str.replace(" ", "_")

df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-01-01,grupo_1,parceiro_a,196,10273,3267,93390
1,2011-01-02,grupo_1,parceiro_a,115,7555,2060,68682
2,2011-01-03,grupo_1,parceiro_a,82,4839,1358,43993
3,2011-01-04,grupo_1,parceiro_a,172,10419,2907,94722
4,2011-01-05,grupo_1,parceiro_a,187,11305,3138,102768

In [9]:
# Transformando numeros em int
df["comissão"] = pd.to_numeric(df["comissão"], errors="coerce")
df["cashback"] = pd.to_numeric(df["cashback"], errors="coerce")
df["vendas_totais"] = pd.to_numeric(df["vendas_totais"], errors="coerce")

df.dtypes

data                    str
grupos_de_usuários      str
parceiro                str
compradores           int64
comissão              int64
cashback              int64
vendas_totais         int64
dtype: object

In [10]:
df["data"] = pd.to_datetime(df["data"], errors="coerce")
df.head()

,data,grupos_de_usuários,parceiro,compradores,comissão,cashback,vendas_totais
0,2011-01-01,grupo_1,parceiro_a,196,10273,3267,93390
1,2011-01-02,grupo_1,parceiro_a,115,7555,2060,68682
2,2011-01-03,grupo_1,parceiro_a,82,4839,1358,43993
3,2011-01-04,grupo_1,parceiro_a,172,10419,2907,94722
4,2011-01-05,grupo_1,parceiro_a,187,11305,3138,102768

In [11]:
df.dtypes

data                  datetime64[us]
grupos_de_usuários               str
parceiro                         str
compradores                    int64
comissão                       int64
cashback                       int64
vendas_totais                  int64
dtype: object

In [12]:
df.shape

(276, 7)

In [15]:
df.isna().any().any()

np.False_